//! The rival agent.
//!
//! A [`HypothesisGenerator`] (an LLM, a heuristic, a fuzzer's corpus) reads a
//! PR and guesses where it breaks. Its output is untrusted: a guess is a
//! [`Hypothesis`], never a [`Finding`] (ADR-6). [`Adversary::triage`] takes
//! those guesses and, for each one that carries a concrete
//! `candidate_input`, runs a harness through the [`Executor`] (the microVM
//! fabric). Only an execution that actually misbehaves becomes a `Finding`,
//! via [`Reproduction::confirm`] / [`Reproduction::confirm_divergence`].
//! Everything else — hallucinations, inputs that don't reproduce, targets we
//! can't harness — ends in [`EngineReport::unreproduced`] for tuning.
//!
//! The consequence the ML engineer accepted when proposing ADR-6: a rival
//! agent that hallucinates costs VM-seconds, never a contributor's reputation.
//! And a prompt-injected agent (the PR body is attacker-controlled) can at
//! worst *miss* bugs; it cannot fabricate one.

pub mod anthropic;

use std::collections::BTreeMap;

pub use anthropic::{parse_hypotheses, AnthropicGenerator, ANTHROPIC_VERSION, DEFAULT_MODEL};
use rebut_core::{
    CommitSha, EngineContext, EngineKind, EngineReport, ExecutionRequest, ExecutionResult,
    Executor, Finding, FnSignature, Hypothesis, Reproduction, Step, Visibility,
};

/// Anything that proposes hypotheses about a PR.
#[async_trait::async_trait]
pub trait HypothesisGenerator: Send + Sync {
    async fn propose(&self, ctx: &EngineContext) -> anyhow::Result<Vec<Hypothesis>>;
}

/// What a replay is checked against.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Oracle {
    /// The head must not panic (or exit non-zero) on the input.
    NoPanic,
    /// The head must behave like the base on the input (unless the declared
    /// intent allows the target's behavior to change).
    Differential,
}

/// How a target function takes its single input.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InputShape {
    Bytes,
    ByteVec,
    Str,
    OwnedString,
}

impl InputShape {
    pub fn of(sig: &FnSignature) -> Option<Self> {
        match sig.args.as_slice() {
            [a] => match a.replace(' ', "").as_str() {
                "&[u8]" => Some(InputShape::Bytes),
                "Vec<u8>" => Some(InputShape::ByteVec),
                "&str" => Some(InputShape::Str),
                "String" => Some(InputShape::OwnedString),
                _ => None,
            },
            _ => None,
        }
    }

    fn is_text(self) -> bool {
        matches!(self, InputShape::Str | InputShape::OwnedString)
    }
}

const START: &[u8] = b"rebut:start\n";

/// Harness program feeding stdin to `sig`. Stdout protocol: `rebut:start`
/// right before the call, then (differential) `rebut:ret:{ret:?}`, then
/// `rebut:done`. A panic exits 101 after `rebut:start`.
pub fn harness_source(sig: &FnSignature, shape: InputShape, oracle: Oracle) -> String {
    let arg = match shape {
        InputShape::Bytes => "&buf",
        InputShape::ByteVec => "buf",
        InputShape::Str => "&text",
        InputShape::OwnedString => "text",
    };
    let mut s = format!(
        "// Harness generated by rebut-adversary for `{}`.\nuse std::io::Read as _;\n\nfn main() {{\n    let mut buf = Vec::new();\n    std::io::stdin().read_to_end(&mut buf).expect(\"stdin\");\n",
        sig.path
    );
    if shape.is_text() {
        s.push_str(
            "    let text = String::from_utf8(buf).expect(\"utf-8 checked by the host\");\n",
        );
    }
    s.push_str("    println!(\"rebut:start\");\n");
    s.push_str(&format!("    let ret = {}({arg});\n", sig.path));
    match oracle {
        Oracle::Differential => s.push_str("    println!(\"rebut:ret:{:?}\", ret);\n"),
        Oracle::NoPanic => s.push_str("    let _ = ret;\n"),
    }
    s.push_str("    println!(\"rebut:done\");\n}\n");
    s
}

/// Triage of untrusted hypotheses.
#[derive(Debug, Clone)]
pub struct Adversary {
    pub oracle: Oracle,
    /// Engine the findings are attributed to (core's `EngineKind` has no
    /// dedicated adversary variant).
    pub engine: EngineKind,
    /// Max hypotheses replayed per PR (VM budget).
    pub max_runs: usize,
    /// Max candidate input size accepted, in bytes.
    pub max_input_bytes: usize,
}

impl Default for Adversary {
    fn default() -> Self {
        Adversary {
            oracle: Oracle::NoPanic,
            engine: EngineKind::Differential,
            max_runs: 16,
            max_input_bytes: 64 * 1024,
        }
    }
}

fn request(
    ctx: &EngineContext,
    repo_url: &str,
    commit: &CommitSha,
    name: String,
    source: String,
    input: Vec<u8>,
) -> ExecutionRequest {
    let b = &ctx.policy.budget;
    ExecutionRequest {
        id: uuid::Uuid::new_v4(),
        repo_url: repo_url.to_string(),
        commit: commit.clone(),
        steps: vec![
            Step::Build {
                profile: "dev".to_string(),
            },
            Step::Harness {
                name,
                source,
                input,
            },
        ],
        timeout_secs: b.vm_timeout_secs,
        vcpus: b.vcpus,
        memory_mib: b.memory_mib,
        sealed: false,
        env: BTreeMap::new(),
    }
}

/// The harness (step 1) started, finished or panicked, but did not time out
/// and did not fail before reaching the call.
fn harness_ran(r: &ExecutionResult) -> bool {
    let built = r.outcomes.iter().any(|o| o.step_index == 0 && o.success());
    let run = r.outcomes.iter().find(|o| o.step_index == 1);
    built && matches!(run, Some(o) if !o.timed_out && o.stdout.starts_with(START))
}

fn vm_secs(r: &ExecutionResult) -> u64 {
    r.outcomes.iter().map(|o| o.duration_ms).sum::<u64>() / 1000
}

impl Adversary {
    /// Replay every hypothesis that carries a candidate input; only confirmed
    /// executions become findings.
    pub async fn triage(
        &self,
        hypotheses: Vec<Hypothesis>,
        executor: &dyn Executor,
        ctx: &EngineContext,
    ) -> anyhow::Result<EngineReport> {
        let mut report = EngineReport::default();
        let mut runs = 0usize;
        for mut h in hypotheses {
            let Some(input) = h.candidate_input.clone() else {
                report.unreproduced.push(h);
                continue;
            };
            let why_not = |h: &mut Hypothesis, why: &str| h.claim.push_str(&format!(" [{why}]"));
            let Some(sig) = ctx
                .plan
                .changed_functions
                .iter()
                .find(|s| s.path == h.target)
            else {
                why_not(&mut h, "target is not a changed function");
                report.unreproduced.push(h);
                continue;
            };
            let Some(shape) = InputShape::of(sig).filter(|_| sig.is_pub) else {
                why_not(&mut h, "no harness for this signature");
                report.unreproduced.push(h);
                continue;
            };
            if input.len() > self.max_input_bytes
                || (shape.is_text() && std::str::from_utf8(&input).is_err())
            {
                why_not(&mut h, "candidate input rejected");
                report.unreproduced.push(h);
                continue;
            }
            if runs >= self.max_runs {
                why_not(&mut h, "adversary run budget exhausted");
                report.unreproduced.push(h);
                continue;
            }
            runs += 1;
            let name = format!("adversary_{runs}");
            let source = harness_source(sig, shape, self.oracle);
            let head = executor
                .execute(request(
                    ctx,
                    &ctx.pr.head_clone_url,
                    &ctx.pr.head_sha,
                    name.clone(),
                    source.clone(),
                    input.clone(),
                ))
                .await?;
            report.vm_seconds += vm_secs(&head);
            if !harness_ran(&head) {
                why_not(&mut h, "harness did not reach the call on head");
                report.unreproduced.push(h);
                continue;
            }
            let finding = match self.oracle {
                Oracle::NoPanic => Reproduction::confirm(
                    &head,
                    1,
                    input,
                    b"exit:Some(0)\nrebut:start\nrebut:done\n".to_vec(),
                )
                .map(|r| {
                    Finding::new(
                        self.engine,
                        "panic",
                        format!("`{}` panics on an adversarial input", sig.path),
                        Visibility::Public,
                        Some(sig.path.clone()),
                        false,
                        r,
                    )
                }),
                Oracle::Differential => {
                    let base = executor
                        .execute(request(
                            ctx,
                            &ctx.pr.base_clone_url,
                            &ctx.pr.base_sha,
                            name,
                            source,
                            input.clone(),
                        ))
                        .await?;
                    report.vm_seconds += vm_secs(&base);
                    if !harness_ran(&base) {
                        why_not(&mut h, "harness did not reach the call on base");
                        report.unreproduced.push(h);
                        continue;
                    }
                    Reproduction::confirm_divergence(&base, 1, &head, 1, input).map(|r| {
                        Finding::new(
                            self.engine,
                            "divergence",
                            format!(
                                "`{}` behaves differently from base on an adversarial input",
                                sig.path
                            ),
                            Visibility::Public,
                            Some(sig.path.clone()),
                            ctx.intent.allows_behavior_change(&sig.path),
                            r,
                        )
                    })
                }
            };
            match finding {
                Some(f) => report.findings.push(f),
                None => {
                    why_not(&mut h, "did not reproduce");
                    report.unreproduced.push(h);
                }
            }
        }
        Ok(report)
    }

    /// Ask a generator, then triage. A failing generator yields an empty
    /// report: the rival agent is an extra, never a reason to be inconclusive.
    pub async fn run(
        &self,
        generator: &dyn HypothesisGenerator,
        ctx: &EngineContext,
    ) -> anyhow::Result<EngineReport> {
        let hyps = match generator.propose(ctx).await {
            Ok(h) => h,
            Err(e) => {
                tracing::warn!(error = %e, "hypothesis generator failed");
                return Ok(EngineReport::default());
            }
        };
        self.triage(hyps, ctx.executor.as_ref(), ctx).await
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rebut_core::{
        ChangeKind, Digest, HypothesisSource, ImpactPlan, PullRequest, RepoId, StepOutcome,
    };
    use std::sync::{Arc, Mutex};

    const BASE: &str = "https://example.invalid/base.git";

    /// Fake fabric. Head version of `mylib::parse::header` panics on inputs
    /// starting with 0xFF; base returns the length for everything.
    #[derive(Default)]
    struct FakeExec {
        calls: Mutex<Vec<ExecutionRequest>>,
    }

    #[async_trait::async_trait]
    impl Executor for FakeExec {
        async fn execute(&self, req: ExecutionRequest) -> anyhow::Result<ExecutionResult> {
            let Step::Harness { input, source, .. } = &req.steps[1] else {
                anyhow::bail!("expected harness")
            };
            let is_base = req.repo_url == BASE;
            let (code, mut stdout) = (Some(0), b"rebut:start\n".to_vec());
            let code = if !is_base && input.first() == Some(&0xFF) {
                Some(101)
            } else {
                if source.contains("rebut:ret") {
                    let ret = if is_base || input.len() < 4 {
                        input.len()
                    } else {
                        4
                    };
                    stdout.extend_from_slice(format!("rebut:ret:{ret}\n").as_bytes());
                }
                stdout.extend_from_slice(b"rebut:done\n");
                code
            };
            let outcomes = vec![
                StepOutcome {
                    step_index: 0,
                    exit_code: Some(0),
                    timed_out: false,
                    stdout: vec![],
                    stderr: vec![],
                    duration_ms: 3000,
                },
                StepOutcome {
                    step_index: 1,
                    exit_code: code,
                    timed_out: false,
                    stdout,
                    stderr: b"thread 'main' panicked".to_vec(),
                    duration_ms: 5,
                },
            ];
            self.calls.lock().unwrap().push(req.clone());
            Ok(ExecutionResult {
                request_id: req.id,
                transcript: ExecutionResult::compute_transcript(&req, &outcomes),
                outcomes,
                environment: Digest::of(b"env"),
            })
        }
    }

    pub(crate) fn ctx(exec: Arc<dyn Executor>) -> EngineContext {
        EngineContext {
            pr: PullRequest {
                repo: RepoId {
                    owner: "o".into(),
                    name: "mylib".into(),
                },
                number: 3,
                base_sha: CommitSha::new("a".repeat(40)).unwrap(),
                head_sha: CommitSha::new("b".repeat(40)).unwrap(),
                head_clone_url: "https://example.invalid/head.git".into(),
                base_clone_url: BASE.into(),
                author: "mallory".into(),
                body: "Refactor header parsing.".into(),
            },
            intent: Default::default(),
            policy: Default::default(),
            plan: ImpactPlan {
                changed_functions: vec![FnSignature {
                    path: "mylib::parse::header".into(),
                    args: vec!["&[u8]".into()],
                    ret: "usize".into(),
                    is_pub: true,
                }],
                changed_files: vec!["src/parse.rs".into()],
                ..Default::default()
            },
            seed: None,
            sealed_specs: vec![],
            executor: exec,
        }
    }

    fn hyp(input: Option<&[u8]>, target: &str) -> Hypothesis {
        Hypothesis {
            source: HypothesisSource::Llm,
            target: target.into(),
            claim: "header() panics on a malformed magic byte".into(),
            candidate_input: input.map(|i| i.to_vec()),
        }
    }

    #[tokio::test]
    async fn hallucination_never_becomes_a_finding() {
        let exec = Arc::new(FakeExec::default());
        let c = ctx(exec.clone());
        let hyps = vec![
            // No input at all: pure prose.
            hyp(None, "mylib::parse::header"),
            // Input that does not trigger anything.
            hyp(Some(b"\x00\x01"), "mylib::parse::header"),
            // Target that is not in the diff.
            hyp(Some(b"\xFF"), "mylib::other::thing"),
        ];
        let r = Adversary::default()
            .triage(hyps, exec.as_ref(), &c)
            .await
            .unwrap();
        assert!(r.findings.is_empty());
        assert_eq!(r.unreproduced.len(), 3);
        assert_eq!(
            exec.calls.lock().unwrap().len(),
            1,
            "only the harnessable one ran"
        );
    }

    #[tokio::test]
    async fn real_crash_becomes_a_finding() {
        let exec = Arc::new(FakeExec::default());
        let c = ctx(exec.clone());
        let r = Adversary::default()
            .triage(
                vec![hyp(Some(b"\xFF\x00"), "mylib::parse::header")],
                exec.as_ref(),
                &c,
            )
            .await
            .unwrap();
        assert_eq!(r.findings.len(), 1);
        let f = &r.findings[0];
        assert_eq!(f.category, "panic");
        assert_eq!(f.reproduction().input(), b"\xFF\x00");
        assert_eq!(
            f.reproduction().observed(),
            b"exit:Some(101)\nrebut:start\n"
        );
        let calls = exec.calls.lock().unwrap();
        assert!(
            matches!(&calls[0].steps[1], Step::Harness { source, .. } if source.contains("mylib::parse::header(&buf)"))
        );
    }

    #[tokio::test]
    async fn differential_oracle_uses_base_as_expectation() {
        let exec = Arc::new(FakeExec::default());
        let mut c = ctx(exec.clone());
        c.intent.kind = ChangeKind::Refactor;
        let adv = Adversary {
            oracle: Oracle::Differential,
            ..Default::default()
        };
        let r = adv
            .triage(
                vec![
                    hyp(Some(b"abcdefgh"), "mylib::parse::header"),
                    hyp(Some(b"ab"), "mylib::parse::header"),
                ],
                exec.as_ref(),
                &c,
            )
            .await
            .unwrap();
        assert_eq!(r.findings.len(), 1);
        assert_eq!(r.findings[0].category, "divergence");
        assert!(r.findings[0].is_actionable());
        assert_eq!(r.unreproduced.len(), 1);
    }

    #[test]
    fn harness_shapes() {
        let sig = FnSignature {
            path: "mylib::p".into(),
            args: vec!["& str".into()],
            ret: "bool".into(),
            is_pub: true,
        };
        let shape = InputShape::of(&sig).unwrap();
        assert_eq!(shape, InputShape::Str);
        let src = harness_source(&sig, shape, Oracle::Differential);
        assert!(src.contains("let ret = mylib::p(&text);"));
        assert!(src.contains("rebut:ret:{:?}"));
        let two = FnSignature {
            args: vec!["u8".into(), "u8".into()],
            ..sig
        };
        assert!(InputShape::of(&two).is_none());
    }
}
