//! Phase-2 receipt signer: an ed25519 key generated inside a TEE and attested
//! to a measured signer build (ADR-5).
//!
//! # What this does and does not buy
//!
//! The attestation proves the private key was generated by, and never left,
//! the measured build. It proves the *receipt* is honest only if that build
//! refuses to sign statements it did not produce or check itself. A
//! [`TeeSigner`] that signs whatever bytes its host hands it (for example
//! behind a `sign(bytes)` RPC from the control plane) protects the key from
//! theft but is a signing oracle for the operator, who can still forge
//! receipts. Moving the verification (or checking of its evidence) into the
//! measured build is what removes operator trust; this type is only the key
//! half of that.
//!
//! Used with [`SoftwareAttestation`](crate::SoftwareAttestation) it offers no
//! security at all.

use ed25519_dalek::{Signer as _, SigningKey, VerifyingKey};

use crate::attest::{attest_key, Attestation, AttestationProvider};
use crate::{Signer, SignerIdentity};

pub struct TeeSigner {
    key: SigningKey,
    attestation: Attestation,
}

impl TeeSigner {
    /// Generates a fresh key and has `provider` attest to it. Must run inside
    /// the TEE; the key exists only in this process's memory.
    pub async fn generate(provider: &dyn AttestationProvider) -> anyhow::Result<Self> {
        let key = SigningKey::generate(&mut rand::rngs::OsRng);
        let attestation = attest_key(provider, &key.verifying_key()).await?;
        Ok(TeeSigner { key, attestation })
    }

    pub fn attestation(&self) -> &Attestation {
        &self.attestation
    }
}

#[async_trait::async_trait]
impl Signer for TeeSigner {
    fn public_key(&self) -> VerifyingKey {
        self.key.verifying_key()
    }

    fn identity(&self) -> SignerIdentity {
        SignerIdentity::Tee {
            attestation: self.attestation.clone(),
        }
    }

    async fn sign(&self, message: &[u8]) -> anyhow::Result<Vec<u8>> {
        Ok(self.key.sign(message).to_bytes().to_vec())
    }
}
